[package]
name = "deccp-aethel"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
deccp-core = { path = "../deccp-core" }
sha2.workspace = true

[dev-dependencies]
ed25519-dalek.workspace = true
serde_json.workspace = true
rand_core = { version = "0.6.4", features = ["getrandom"] }

